### ISSUE TITLE
Some tickers inaccessible

### ISSUE THREAD

**Issue by lmlask** [Julien-R44/cli-candlestick-chart#11]
Some valid tickers lead to panic when fetching from Yahoo Finance, even though they are valid. Observed that on exchanges outside the US. Examples are `PETR4.SA` and `GGBR4.SA.`  

Maybe Alpha Vantage would be able to deal with those better? I know Yahoo has a history of making things difficult for this kind of use.

Sometimes other tickers (such as `ETH-USD`) also break, but that appears to be random or based on time of request.

**Comment by Julien-R44** [comment]
Yes I also noticed that Yahoo Finance was not a very reliable source.
I am thinking of removing the *-fetch mode from cli-candlestick-chart. In my opinion the real role of this library is mainly to provide an API to draw charts in the terminal, not to be a bridge to brokers/data-sources. 

Someone could build a tool on cli-candlestick-chart that would allow to fetch charts coming from several brokers/exchanges, that could be great, but indeed I don't think that is the role of cli-candlestick-chart
