### ISSUE TITLE
Project compatibility

### ISSUE THREAD

**Issue by docop** [Julien-R44/cli-candlestick-chart#12]
Hi  So your project idea is quite great actually to have chart draw in terminal. Perhaps, if you can also add an appimage version, that could be very nice to run on all linux.
thanks

**Comment by Julien-R44** [comment]
What is your OS? The current build should run on most current Linux systems. 
However I don't really feel like doing AppImage builds with Github Actions. Feel free to send a PR if you want to.
If you have an exotic system you can always build from source, it's very easy
