### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by BoboTiG** [Julien-R44/cli-candlestick-chart#14]
Hello Julien,

This is an amazing library, thanks a lot for your work! :heart_on_fire: 

I was looking for an similar solution on Python, and found nothing I was really interested in. So here it is, I created a Python version of your project: https://github.com/BoboTiG/py-candlestick-chart

I hope it is OK on your side, it will be kept open-source, nothing fancy more. I plan to ease integration with Textual/Rich, which are other cool terminal libraries on Python.

Let me know if you find any issue with my move, otherwise I'll delete my repository ;)

Cheers,

Mickaël

**Comment by Julien-R44** [comment]
Hey Mickaël! 👋 
Thanks for the kind words!

I don't have any problem with that, it's great to have taken this initiative, I think it will be useful to many people because Python is still much more popular than Rust!

I will add a note in the readme with a link to your repo.

Thanks 🚀
